stages:
  - sync

sync_to_mirrors:
  stage: sync
  image: alpine:latest
  before_script:
    # 安裝必要工具
    - apk add --no-cache git openssh-client curl bash
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash

    # 啟動 SSH Agent 並載入安全檔案中的私鑰
    - eval $(ssh-agent -s) > /dev/null
    #
    - chmod 400 .secure_files/sync_bot
    - ssh-add .secure_files/sync_bot > /dev/null 2>&1

    # 建立信任主機
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan github.com codeberg.org >> ~/.ssh/known_hosts 2>/dev/null

    # 設定 Bot 身份
    - git config --global user.email "TW0hank0@noreply.codeberg.org"
    - git config --global user.name "sync-bot-TW0hank0"

  script:
    # 設定遠端並推送
    - git remote add github git@github.com:TW0hank0/positive_mahjong.git
    - git remote add codeberg git@codeberg.org:TW0hank0/positive_mahjong.git

    # 鏡像同步
    - git push --mirror github
    - git push --mirror codeberg

  rules:
    - if: $CI_COMMIT_BRANCH == "master"
