accepted = [
    "Apache-2.0",
    "MIT",
    "AGPL-3.0-only",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "CC0-1.0",
    "NCSA",
    "ISC",
    "0BSD",
    "Unicode-3.0",
    "OpenSSL",
    "CDLA-Permissive-2.0",
    "GPL-3.0-only",
]

#threshold = 1.0
#[licenses]
#self_cell = "Apache-2.0 OR GPL-2.0-only"
#name = "self_cell"
#expression = "Apache-2.0"

ignore-build-dependencies = false
ignore-dev-dependencies = false

[codespan.clarify]
license = "Apache-2.0"

[[codespan.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[codespan-reporting.clarify]
license = "Apache-2.0"

[[codespan-reporting.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[failure_derive.clarify]
license = "Apache-2.0 OR MIT"

[[failure_derive.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[ring]
accepted = ["OpenSSL"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[webpki-roots]
accepted = ["MPL-2.0"]
