# SPDX-License-Identifier: AGPL-3.0-only
# 著作權所有 (C) 2026 TW0hank0
#
# 本檔案屬於 positive_mahjong 專案的一部分。
# 專案儲存庫：https://gitlab.com/TW0hank0/positive_mahjong
#
# 本程式為自由軟體：您可以根據自由軟體基金會發佈的 GNU Affero 通用公共授權條款
# 第 3 版（僅此版本）重新發佈及/或修改本程式。
#
# 本程式的發佈是希望它能發揮功用，但不提供任何擔保；
# 甚至沒有隱含的適銷性或特定目的適用性擔保。詳見 GNU Affero 通用公共授權條款。
#
# 您應該已經收到一份 GNU Affero 通用公共授權條款副本。
# 如果沒有，請參見 <https://www.gnu.org/licenses/>。

[workspace.package]
authors = ["TW0hank0 <public.email.hank@tutamail.com>"]
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://gitlab.com/TW0hank0/positive_mahjong"
rust-version = "1.94"
version = "0.1.1"

[workspace.dependencies]
# --- local ---
pmj_gamemodes = { path = "crates/pmj_gamemodes" }
pmj_shared = { path = "crates/pmj_shared" }
pmj_client_core = { path = "crates/pmj_client_core" }
positive_mahjong = { path = "." }
# --- shared ---
dirs = "=6.0.0"
godot = { version = "=0.5.5", features = ["api-4-6"] }
iced = { version = "=0.14.0", features = [
    "advanced",
    "canvas",
    "debug",
    "fira-sans",
    "image",
    "lazy",
    "linux-theme-detection",
    "svg",
    "thread-pool",
    "tiny-skia",
    "wayland",
    "wgpu",
    "x11",
] }
image = { version = "=0.25.10", features = [
    "bmp",
    "exr",
    "ff",
    "gif",
    "hdr",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "qoi",
    "tga",
    "tiff",
    "webp",
] }
local-ip-address = "=0.6.13"
lyon_algorithms = "=1.0.21"
positive_tool_rs = { git = "https://gitlab.com/TW0hank0/positive_tool_rs.git", rev = "4467e45d" }
rand = "=0.10.2"
serde = { version = "=1.0.229", features = ["derive", "serde_derive"] }
serde_json = "=1.0.151"
tracing = { version = "=0.1.44" }
tracing-appender = { version = "=0.2.5" }
tungstenite = { version = "=0.30.0", features = [
    "rustls-tls-webpki-roots",
    "rustls-tls-native-roots",
] }
url = "=2.5.8"
clap = { version = "=4.6.6", features = ["derive"]}
crossbeam = "=0.8.4"
rayon = "1.12.0"
# --- wasm ---
console_error_panic_hook = { version = "=0.1.7" }
wasm-bindgen = { version = "=0.2.128" }

[workspace]
members = [
    "crates/pmj_client_cross/rust",
    "crates/pmj_client_desktop",
    "crates/pmj_client_desktop_base",
    "crates/pmj_gamemodes",
    "crates/pmj_server",
    "crates/pmj_shared",
    "crates/pmj_client_core"
]
resolver = "3"

[profile.release]
debug = true
lto = true
opt-level = 3
codegen-units = 1
incremental = false

[profile.dev]
debug = true
lto = false
opt-level = 0
