version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 TW0hank0"
SPDX-License-Identifier = "AGPL-3.0-only"
path = [
    ".cargo/*",
    ".editorconfig",
    ".forgejo/**",
    ".gitattributes",
    ".github/**",
    ".gitignore",
    ".gitlab-ci.yml",
    ".gitlab/**",
    ".zed/*",
    "CHANGELOG.md",
    "Cargo.lock",
    "Cargo.toml",
    "README.md",
    "READMEs/**",
    "ROADMAP.md",
    "TODO.md",
    "about.toml",
    "assets/icon/*",
    "ci-cache-version.json",
    "crates/pmj-client-core/**",
    "crates/pmj-client-cross/**",
    "crates/pmj-client-desktop-base/**",
    "crates/pmj-client-desktop/**",
    "crates/pmj-desktop/Cargo.toml",
    "crates/pmj-desktop/src/lib.rs",
    "crates/pmj-desktop/src/shared.rs",
    "crates/pmj-gamemodes/**",
    "crates/pmj-server-desktop/**",
    "crates/pmj-shared/**",
    "deny.toml",
    "docs/**",
    "renovate.json",
    "rust-toolchain.toml",
    "scripts/**",
    "supply-chain/*",
    "taplo.toml",
    "templates/*",
    "website/**",
]
precedence = "override"

# Third Party

[[annotations]]
SPDX-FileCopyrightText = "2014-2021 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'"
SPDX-License-Identifier = "LicenseRef-Noto-Sans-TC"
path = "assets/Noto_Sans_TC/**"
precedence = "override"

[[annotations]]
SPDX-FileCopyrightText = "2022-2026 Google LLC"
SPDX-License-Identifier = "Apache-2.0"
path = "assets/material_symbols/*"
precedence = "override"

[[annotations]]
SPDX-FileCopyrightText = "2019 Héctor Ramón, Iced contributors"
SPDX-License-Identifier = "LicenseRef-Iced"
path = [
    "crates/pmj-desktop/src/circular.rs",
    "crates/pmj-desktop/src/easing.rs",
]
precedence = "override"
