exclude = [
  "**/.venv/**",
  "auto_generated/**",
  "docs/book/**",
  "target/**",
  "web/**",
]

include = ["Cargo.toml", "**/Cargo.toml", "**/*.toml"]

[formatting]
align_comments = true
align_entries = false
array_trailing_comma = true
reorder_arrays = true
reorder_keys = true
indent_string = "    "
