name: 錯誤回報（Bug report）
description: 回報非預期行為
title: "[Bug] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        填寫此issue前，請確認沒有重复的issue。

  - type: textarea
    attributes:
      label: 目前行為
      description: |
        目前行為
    validations:
      required: true

  - type: textarea
    attributes:
      label: 正常行為
      description: |
        正常行為
    validations:
      required: true

  - type: checkboxes
    id: know
    attributes:
      label: 這個issue是唯一的
      options:
        - label: I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索問題追踪器并且没有發現相同的 issue。
          required: true
