import { Button } from "std-widgets.slint";
import {
    MaterialText,
    ScrollView,
} from "../material/material.slint";

export { MaterialWindowAdapter } from "../material/material.slint";

export component MainWindow inherits Window {
    //width: 1080px;
    //height: 720px;
    title: "PositiveMahjong Client";
    min-width: 540px;
    min-height: 360px;
    max-width: 10800px;
    max-height: 72000px;
    //background: darkgray;
    default-font-size: 30px;
    VerticalLayout {
        spacing: 20px;
        padding: 20px;
        Text {
            text: "PMJ Client";
            font-size: 35px;
            horizontal-alignment: TextHorizontalAlignment.left;
            //color: lightgray;
        }

        TextInput {
            //placeholder-text: "輸入資料...";
            text <=> root.server_ip;
            single-line: true;
            //color: lightgray;
        }

        Button {
            text: "測試連線";
            clicked => {
                root.test_connection();
            }
        }

        ScrollView {
            MaterialText {
                text: root.server_response_text;
                horizontal-alignment: TextHorizontalAlignment.left;
                //color: Colors.rgba();
                wrap: TextWrap.word-wrap;
            }

            vertical-scrollbar-policy: ScrollBarPolicy.always-on;
            horizontal-scrollbar-policy: ScrollBarPolicy.always-on;
        }
    }

    // 屬性與回調定義
    in-out property <string> server_response_text: "";
    in-out property <string> server_ip: "請輸入伺服器Ip";
    callback test_connection();
}
