# SPDX-License-Identifier: AGPL-3.0-only
# 版權所有 (C) 2026 TW0hank0
#
# 本檔案屬於 positive_mahjong 專案的一部分。
# 專案儲存庫：https://gitlab.com/TW0hank0/positive_mahjong
#
# 本程式為自由軟體：您可以根據自由軟體基金會發佈的 GNU Affero 通用公共授權條款
# 第 3 版（僅此版本）重新發佈及/或修改本程式。
#
# 本程式的發佈是希望它能發揮功用，但不提供任何擔保；
# 甚至沒有隱含的適銷性或特定目的適用性擔保。詳見 GNU Affero 通用公共授權條款。
#
# 您應該已經收到一份 GNU Affero 通用公共授權條款副本。
# 如果沒有，請參見 <https://www.gnu.org/licenses/>。
name: commit-ci
on:
  # 支援在 GitHub 上手動點擊觸發
  workflow_dispatch: 
  push:
    branches:
      - master
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # x86_64
          - ubuntu-latest
          # arm64
          - ubuntu-26.04-arm
          # x86_64
          - windows-latest
          # arm64
          - windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Install Dep
        uses: ./.github/workflows/instdep
      - name: Save Cache Cargo installed tools on Linux
        uses: actions/cache/save@v6.1.0
        if: runner.os == 'Linux'
        with:
          path: |
            ~/.cargo/bin/cargo-deny
            ~/.cargo/bin/cargo-about
            ~/.cargo/bin/mdbook
            ~/.cargo/bin/cargo-msrv
            ~/.cargo/bin/taplo
            ~/.cargo/bin/eza
            ~/.cargo/bin/wild
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-tools-${{ hashFiles('ci-cache-version.json') }}
      - name: Save Cache Cargo installed tools on Windows
        uses: actions/cache/save@v6.1.0
        if: runner.os == 'Windows'
        with:
          path: |
            ~/.cargo/bin/cargo-deny.exe
            ~/.cargo/bin/cargo-about.exe
            ~/.cargo/bin/mdbook.exe
            ~/.cargo/bin/cargo-msrv.exe
            ~/.cargo/bin/taplo.exe
            ~/.cargo/bin/eza.exe
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-tools-${{ hashFiles('ci-cache-version.json') }}
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # x86_64
          - ubuntu-latest
          # arm64
          - ubuntu-26.04-arm
          # x86_64
          - windows-latest
          # arm64
          - windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Install Dep
        uses: ./.github/workflows/instdep
      - name: Prepare venv
        run: |
          cd scripts
          uv venv
          uv sync
          cd ..
      - name: Run debug check
        run: cargo check --workspace
      - name: Run release check
        run: cargo check --release --workspace
      - name: Run clippy
        run: cargo clippy
      - name: Run License Check
        run: |
          cd scripts
          uv run license_check.py
          cd ..
      - name: Lint toml file
        run: taplo lint
      - name: ruff check scripts
        run: |
          cd scripts
          ruff check .
          cd ..
      - name: ty check scripts
        run: |
          cd scripts
          ty check .
          cd ..
      - name: Run cargo-deny
        run: |
          cargo deny fetch
          cargo deny check
  build_client_desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # x86_64
          - ubuntu-latest
          # arm64
          - ubuntu-26.04-arm
          # x86_64
          - windows-latest
          # arm64
          - windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - uses: ./.github/workflows/instdep
      - name: Prepare venv
        run: |
          cd scripts
          uv venv
          uv sync
          cd ..
      - name: use build script
        env:
          CARGO_BUILD_JOBS: 1  # 限制為單線程，避免 OOM Killer
        run: |
          cd scripts
          uv run build_desktop.py
          cd ..
      - name: get version on Linux
        id: get_version_linux
        if: runner.os == 'Linux'
        run: |
          cd scripts
          file=$(uv run util.py get version)
          echo "version=$file" >> $GITHUB_OUTPUT
          cd ..
      - name: get version on Windows
        id: get_version_windows
        if: runner.os == 'Windows'
        run: |
          cd scripts
          $file = (uv run util.py get version)
          echo "version=$file" >> $env:GITHUB_OUTPUT
          cd ..
      - name: Upload desktop artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: client_desktop-${{ runner.os }}-${{ runner.arch }}
          path: artifacts
  release_artifacts:
    needs:
      - build_client_desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@v7.0.1
      - uses: ./.github/workflows/instdep
      - name: prepare CI Venv
        run: |
          cd scripts
          uv venv
          uv sync
          cd ..
      - name: download all artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
      - name: List Dir
        run: |
          eza --tree .
      - name: release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODEBERG_PAT_TOKEN: ${{ secrets.CODEBERG_PAT_TOKEN }}
          GITLAB_PAT_TOKEN: ${{ secrets.GL_PAT }}
        run: |
          cd scripts
          uv run releases.py
          cd ..
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - uses: ./.github/workflows/instdep/
      - name: Build license
        run: |
          cd scripts
          uv run build_license.py
          cd ..
      - name: Build doc and website
        run: |
          cd scripts
          uv run build_website.py
          cd ..
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: ./website_build/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5.0.1
  deploy_with_artifacts:
    needs:
      - build_client_desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - uses: ./.github/workflows/instdep/
      - name: download all artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
      - name: Build license
        run: |
          cd scripts
          uv run build_license.py
          cd ..
      - name: Build doc and website
        run: |
          cd scripts
          uv run build_website.py
          cd ..
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          name: pages-with-artifacts
          path: ./website_build/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5.0.1
        with:
          artifact_name: pages-with-artifacts
