name: commit-build

on:
  push:
    paths-ignore:
      - "README.md"
      - "READMEs/**"
      - ".vscode/**"
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout Secret
        #if: matrix.target-platform == 'Android'
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.SECRET_REPO }}
          token: ${{ secrets.SECRET_REPO_TOKEN }} # Repo token
          path: secret

      - name: install cargo-apk
        run: |
          cargo install cargo-apk

      - name: build apk
        run: |
          uv run scripts/build_script_android.py
