name: Renovate GitLab Projects

on:
  # 設定定時觸發（每週一早上 10 點 UTC）
  schedule:
    - cron: "0 10 * * 1"
  # 支援在 GitHub 上手動點擊觸發
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Renovate against GitLab
        uses: renovatebot/github-action@v41.0.1
        with:
          renovate-image: renovate/renovate:latest
        env:
          # 告訴 Renovate 平臺是 GitLab
          RENOVATE_PLATFORM: "gitlab"
          # 帶入 GitLab PAT
          RENOVATE_TOKEN: ${{ secrets.GL_PAT }}
          # 指定目標 GitLab 專案
          # 若有多個專案可用空格隔開，如 'org/repo1 org/repo2'
          RENOVATE_EXTRA_FLAGS: "TW0hank0/positive_mahjong"
