name: Renovate GitLab Projects

on:
  # 設定定時觸發（每週一早上 10 點 UTC）
  schedule:
    - cron: "0 10 * * 1"
  # 支援在 GitHub 上手動點擊觸發
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Renovate against GitLab
        uses: renovatebot/github-action@v46.2.2
        env:
          # 告訴 Renovate 平臺是 GitLab
          RENOVATE_PLATFORM: "gitlab"
          # 帶入 GitLab PAT
          RENOVATE_TOKEN: ${{ secrets.GL_PAT }}
          # Github Pat
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
          # 指定目標 GitLab 專案
          # 若有多個專案可用空格隔開，如 'org/repo1 org/repo2'
          RENOVATE_REPOSITORIES: "TW0hank0/positive_mahjong"
        with:
          # 明確指定與 Action 版本相容的 Renovate 版本
          renovate-version: "39"
